################################################################################
#
# SEÇÃO: Organizações
#   --> Esta seção define as diferentes identidades organizacionais 
#     que serão referenciadas posteriormente na configuração.
#
# ARQUIVO configtxgen contém as configurações:
#   --> do nó ordenador (OrdererOrg); 
#   --> das organizações participantes (Produtor, Transportador e Consumidor);
#   --> dos peers âncora (anchor peer) de cada organização
#
# ANCHOR PEER
#   --> é a porta de entrada (ou saída) para comunicação de
#       uma organização com os demais participantes da Rede
#       (Protocolo GOSSIP)
#   --> cada organização precisa ter PELO MENOS um anchor peer
#
################################################################################

Organizations:
   
    - &OrdererOrg 
        #   DefaultOrg define a organização que é usada no sampleconfig 
        #   do ambiente de desenvolvimento fabric.git
        Name: OrdererOrg

        # ID para carregar a definição do MSP como
        ID: OrdererMSP
        
        # MSPDir: é o caminho do sistema de arquivos (filesystem path) que contém a configuração do MSP
        MSPDir: crypto-config/ordererOrganizations/sampledomain.com/msp

    - &Produtor 
        Name: ProdutorMSP
        ID: ProdutorMSP
        MSPDir: crypto-config/peerOrganizations/produtor.sampledomain.com/msp
        AnchorPeers:
            # --> define a localização dos peers que podem ser usados 
            #     para comunicação entre organizações (Protocolo Gossip). 
            # --> esse valor é codificado apenas no bloco genesis no  
            #     contexto da seção Application
            - Host: peer0.produtor.sampledomain.com
              Port: 7051
            
    - &Transportador
        Name: TransportadorMSP
        ID: TransportadorMSP
        MSPDir: crypto-config/peerOrganizations/transportador.sampledomain.com/msp
        AnchorPeers:
            - Host: peer0.transportador.sampledomain.com
              Port: 7051
    
    - &Vendedor
        Name: VendedorMSP
        ID: VendedorMSP
        MSPDir: crypto-config/peerOrganizations/vendedor.sampledomain.com/msp
        AnchorPeers:
            - Host: peer0.vendedor.sampledomain.com
              Port: 7051