# Copyright 2018 Villa Labs All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

################################################################################
#
# SEÇÃO: Organizações
#   --> Esta seção define as diferentes identidades organizacionais 
#     que serão referenciadas posteriormente na configuração.
#
# ARQUIVO configtxgen contém as configurações:
#   --> do nó ordenador (OrdererOrg); 
#   --> das organizações participantes (Produtor, Transportador e Consumidor);
#   --> dos peers âncora (anchor peer) de cada organização
#
# ANCHOR PEER
#   --> é a porta de entrada (ou saída) para comunicação de
#       uma organização com os demais participantes da Rede
#       (Protocolo GOSSIP)
#   --> cada organização precisa ter PELO MENOS um anchor peer
#
################################################################################
Organizations:
   
    - &OrdererOrg
        #   DefaultOrg define a organização que é usada no sampleconfig 
        #   do ambiente de desenvolvimento fabric.git
        Name: OrdererOrg

        # ID para carregar a definição do MSP como
        ID: OrdererMSP

        # MSPDir: é o caminho do sistema de arquivos (filesystem path) que contém a configuração do MSP
        MSPDir: crypto-config/ordererOrganizations/sampledomain.com/msp

    - &Produtor
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment 
        Name: ProdutorMSP

        # ID to load the MSP definition as
        ID: ProdutorMSP

        MSPDir: crypto-config/peerOrganizations/produtor.sampledomain.com/msp
        
        AnchorPeers:
            # --> define a localização dos peers que podem ser usados 
            #     para comunicação entre organizações (Protocolo Gossip). 
            # --> esse valor é codificado apenas no bloco genesis no  
            #     contexto da seção Application
            - Host: peer0.produtor.sampledomain.com
              Port: 7051

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer.sampledomain.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    OrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Produtor
    OrgChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Produtor
