# Copyright 2018 Sample Domain All Rights Reserved
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

#versão do Docker-Compopse que está sendo utilizada
version: '2'

networks:
  sampleNetwork:

#Volume: cria uma cópia dos dados que estão no container para a nossa máquina (repositório local)
volumes:
  #=== Certificados de Autoridade ===#
  ca.produtor.sampledomain.com:
  ca.transportador.sampledomain.com:
  ca.vendedor.sampledomain.com:
  #=== Ordenador ===#
  orderer.sampledomain.com:
  #=== Produtor ===#
  peer0.produtor.sampledomain.com:
  couchdb.peer0.produtor.sampledomain.com:
  peer1.produtor.sampledomain.com:
  couchdb.peer1.produtor.sampledomain.com:
  #=== Transportador ===#
  peer0.transportador.sampledomain.com:
  couchdb.peer0.transportador.sampledomain.com:
  peer1.transportador.sampledomain.com:
  couchdb.peer1.transportador.sampledomain.com:
  #=== Vendedor ===#
  peer0.vendedor.sampledomain.com:
  couchdb.peer0.vendedor.sampledomain.com:
  peer1.vendedor.sampledomain.com:
  couchdb.peer1.vendedor.sampledomain.com:
  
#SERVICES: informar quais containers serão criados
#ou seja, quais serão os serviços (services) que o Compose vai subir
services:
  ca.produtor.sampledomain.com:                     #nome do Serviço
    container_name: ca.produtor.sampledomain.com    #nome do container
    image: hyperledger/fabric-ca                    #imagem que será usada como referência p/ a criação do container
    environment:                                    #variáveis de ambiente
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.produtor.sampledomain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.produtor.sampledomain.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
    ports:
      - "7054:7054"         #portas que o container irá usar (no esquema: {host_port}:{container_port})
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/produtor.sampledomain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - sampleNetwork       #rede pela qual serão feitas as comunicações
  
  ca.transportador.sampledomain.com:
    container_name: ca.transportador.sampledomain.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.transportador.sampledomain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.transportador.sampledomain.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/transportador.sampledomain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - sampleNetwork

  ca.vendedor.sampledomain.com:
    container_name: ca.vendedor.sampledomain.com
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.vendedor.sampledomain.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.vendedor.sampledomain.com-cert.pem
      #- FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/42215d11328cb5dcc2054e4b4652a4174de4bb10e77e593d371a8a178da365a0_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/vendedor.sampledomain.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - sampleNetwork

  orderer.sampledomain.com:
    container_name: orderer.sampledomain.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer   #isso aqui pode me dar dor de cabeça!
    command: orderer
    ports:
      - 7050:7050
    volumes:
      - ./channel-artifacts/:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/sampledomain.com/orderers/orderer.sampledomain.com/:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/produtor.sampledomain.com/peers/peer0.produtor.sampledomain.com/:/etc/hyperledger/msp/peerProdutor
    networks:
      - sampleNetwork

  #=== Produtor ===#
  peer0.produtor.sampledomain.com:
    container_name: peer0.produtor.sampledomain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.produtor.sampledomain.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=ProdutorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.produtor.sampledomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.produtor.sampledomain.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.produtor
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/produtor.sampledomain.com/peers/peer0.produtor.sampledomain.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/produtor.sampledomain.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.sampledomain.com
    networks:
      - sampleNetwork

  peer1.produtor.sampledomain.com:
    container_name: peer1.produtor.sampledomain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.produtor.sampledomain.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING=debug
      - CORE_PEER_LOCALMSPID=ProdutorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.produtor.sampledomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.produtor.sampledomain.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1.produtor
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/produtor.sampledomain.com/peers/peer1.produtor.sampledomain.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/produtor.sampledomain.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.sampledomain.com
    networks:
      - sampleNetwork

  couchdb.peer0.produtor.sampledomain.com:
    container_name: couchdb.peer0.produtor.sampledomain.com
    environment:
      - COUCHDB_USER=peer0.produtor
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports: 
      - 5984:5984
    networks: 
      - sampleNetwork

  couchdb.peer1.produtor.sampledomain.com:
    container_name: couchdb.peer1.produtor.sampledomain.com
    environment:
      - COUCHDB_USER=peer1.produtor
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports: 
      - 6984:5984
    networks: 
      - sampleNetwork

  #=== Transportador ===#
  peer0.transportador.sampledomain.com:
    container_name: peer0.transportador.sampledomain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.transportador.sampledomain.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=TransportadorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.transportador.sampledomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.transportador.sampledomain.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.transportador
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/transportador.sampledomain.com/peers/peer0.transportador.sampledomain.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/transportador.sampledomain.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.sampledomain.com
      - couchdb.peer0.transportador.sampledomain.com
    networks:
      - sampleNetwork

  peer1.transportador.sampledomain.com:
    container_name: peer1.transportador.sampledomain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.transportador.sampledomain.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=TransportadorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.transportador.sampledomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.transportador.sampledomain.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1.transportador
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 10051:7051
      - 10053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/transportador.sampledomain.com/peers/peer1.transportador.sampledomain.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/transportador.sampledomain.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.sampledomain.com
      - couchdb.peer1.transportador.sampledomain.com
    networks:
      - sampleNetwork

  couchdb.peer0.transportador.sampledomain.com:
    container_name: couchdb.peer0.transportador.sampledomain.com
    environment:
      - COUCHDB_USER=peer0.transportador
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 7984:5984
    networks:
      - sampleNetwork

  couchdb.peer1.transportador.sampledomain.com:
    container_name: couchdb.peer1.transportador.sampledomain.com
    environment:
      - COUCHDB_USER=peer1.transportador
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 8984:5984
    networks:
      - sampleNetwork
  
  #=== Vendedor ===#
  peer0.vendedor.sampledomain.com:
    container_name: peer0.vendedor.sampledomain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.vendedor.sampledomain.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=VendedorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.vendedor.sampledomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.vendedor.sampledomain.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0.vendedor
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 11051:7051
      - 11053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/vendedor.sampledomain.com/peers/peer0.vendedor.sampledomain.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/vendedor.sampledomain.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.sampledomain.com
      - couchdb.peer0.vendedor.sampledomain.com
    networks:
      - sampleNetwork
  
  peer1.vendedor.sampledomain.com:
    container_name: peer1.vendedor.sampledomain.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1.vendedor.sampledomain.com
      - FABRIC_LOGGING_SPEC=info
      - CORE_CHAINCODE_LOGGING_LEVEL=info
      - CORE_PEER_LOCALMSPID=TransportadorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer1.vendedor.sampledomain.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=network_sampleNetwork
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.vendedor.sampledomain.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1.vendedor
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=password
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    # command: peer node start --peer-chaincodedev=true
    ports:
      - 12051:7051
      - 12053:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/vendedor.sampledomain.com/peers/peer1.vendedor.sampledomain.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/vendedor.sampledomain.com/users:/etc/hyperledger/msp/users
      - ./channel-artifacts:/etc/hyperledger/configtx
    depends_on:
      - orderer.sampledomain.com
      - couchdb.peer1.vendedor.sampledomain.com
    networks:
      - sampleNetwork

  couchdb.peer0.vendedor.sampledomain.com:
    container_name: couchdb.peer0.vendedor.sampledomain.com
    environment:
      - COUCHDB_USER=peer0.vendedor
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 9984:5984
    networks:
      - sampleNetwork

  couchdb.peer1.vendedor.sampledomain.com:
    container_name: couchdb.peer1.vendedor.sampledomain.com
    environment:
      - COUCHDB_USER=peer1.vendedor
      - COUCHDB_PASSWORD=password
    image: hyperledger/fabric-couchdb
    ports:
      - 10984:5984
    networks:
      - sampleNetwork

  #====== CLI ======#
  cli:                #CLI: container que permite acessar cada nó participante da rede                         
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.produtor.sampledomain.com:7051
      - CORE_PEER_LOCALMSPID=ProdutorMSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/produtor.sampledomain.com/users/Admin@produtor.sampledomain.com/msp
      - CORE_CHAINCODE_KEEPALIVE=10
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ../fabric-samples/chaincode/:/opt/gopath/src/github.com/
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/config/
    networks:
        - sampleNetwork
    depends_on:
      - orderer.sampledomain.com
      - peer0.produtor.sampledomain.com
      - peer1.produtor.sampledomain.com
      - peer0.transportador.sampledomain.com
      - peer1.transportador.sampledomain.com
      - peer0.vendedor.sampledomain.com
      - peer1.vendedor.sampledomain.com

